### ISSUE TITLE
Cant install EFMFD using sileo

### ISSUE THREAD

**Issue by dablincx** [PoomSmart/EFM-Font-Downloader#1]
The download fails with error 404

![EB771BE6-F4F6-4D2D-9C6F-DB9DD823D6B0](https://github.com/PoomSmart/EFM-Font-Downloader/assets/80812233/fa0ba010-fc49-4f8e-aa77-c95a75451e5f)

everything else can be downloaded fine

System Information if needed:
 - iOS 15.1
 - palera1n
 - 6s+ (A9)

**Comment by PoomSmart** [comment]
Refresh source?

**Comment by dablincx** [comment]
that did in fact work and i believe that i am stupid 💀
